### ISSUE TITLE
Crashes after attempting login

### ISSUE THREAD

**Issue by yochananmarqos** [20PercentRendered/opensteamclient#1] opened 2023-04-27 20:15 UTC
<details>
<summary>Using QR code:
</summary>

```
❯ opensteam
Initialized thread CallbackThread
Initialized thread LoginThread
Initialized thread ComputerInUse

(opensteam:1695552): dbind-WARNING **: 13:40:39.620: Couldn't connect to accessibility bus: Failed to connect to socket /run/user/1000/at-spi/bus_1: No such file or directory
qt.dbus.integration: Could not connect "org.freedesktop.IBus" to globalEngineChanged(QString)
Relaunching
Initialized thread CallbackThread
Initialized thread LoginThread
Initialized thread ComputerInUse

(opensteam:1695552): dbind-WARNING **: 13:40:39.724: Couldn't connect to accessibility bus: Failed to connect to socket /run/user/1000/at-spi/bus_1: No such file or directory
qt.dbus.integration: Could not connect "org.freedesktop.IBus" to globalEngineChanged(QString)
Launched correctly, opensteam_marker is inside this directory
Failed to dlopen steamclient.so: cannot open shared object file: No such file or directory
Failed to load steamclient.so; verifying and restarting. 
Downloading https://client-update.akamai.steamstatic.com/bins_ubuntu12.zip.9151f0a5f3363cd297840f33644ed03638709121 started
Downloaded successfully
Installing ubuntu12_32/fossilize_replay with size 2656122
Installing ubuntu12_32/gameoverlayrenderer.so with size 346683
Installing ubuntu12_32/gameoverlayui.so with size 7111150
Installing ubuntu12_32/steamclient.so with size 37230206
Installing ubuntu12_32/steamservice.so with size 5299867
Installing ubuntu12_64/fossilize_replay with size 2615238
Installing ubuntu12_64/gameoverlayrenderer.so with size 321284
Installing ubuntu12_64/streaming_client with size 12987734
Downloading https://client-update.akamai.steamstatic.com/bins_sdk_ubuntu12.zip.af7a25a5fb81483cccce95b6c6c6ac230d072817 started
Downloaded successfully
Installing linux32/crashhandler.so with size 663781
Installing linux32/steamclient.so with size 36595751
Installing linux32/steamerrorreporter with size 137871
Installing linux64/crashhandler.so with size 678444
Installing linux64/steamclient.so with size 35097585
Downloading https://client-update.akamai.steamstatic.com/bins_misc_ubuntu12.zip.851e81bcc68f13ade0314d4ee84e8c0425942cb6 started
Downloaded successfully
Installing GameOverlayRenderer64.dll with size 1414504
Installing bin/d3ddriverquery64.exe with size 145768
Installing legacycompat/Steam.dll with size 385312
Installing legacycompat/SteamService.exe with size 2812312
Installing legacycompat/iscriptevaluator.exe with size 494440
Installing steamclient.dll with size 19018088
Installing steamclient64.dll with size 22342352
Installing ubuntu12_32/gldriverquery with size 108987
Installing ubuntu12_32/vulkandriverquery with size 141735
Installing ubuntu12_64/disk-free with size 9013
Installing ubuntu12_64/gldriverquery with size 124744
Installing ubuntu12_64/vulkandriverquery with size 139303
Relaunching
Initialized thread CallbackThread
Initialized thread LoginThread
Initialized thread ComputerInUse

(opensteam:1695552): dbind-WARNING **: 13:40:42.797: Couldn't connect to accessibility bus: Failed to connect to socket /run/user/1000/at-spi/bus_1: No such file or directory
qt.dbus.integration: Could not connect "org.freedesktop.IBus" to globalEngineChanged(QString)
Launched correctly, opensteam_marker is inside this directory
Starting GUI
Steam client service's PID is 1695580
Starting CallbackThread
Started CallbackThread
Starting LoginThread
Started LoginThread
Starting ComputerInUse
Started ComputerInUse
steamclient.so Found CLIENTENGINE_INTERFACE_VERSION005 at 0x7f80bfd84f00
Creating new GlobalUser
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Forced create but already created for SharedObjectEvent
Forced create but already created for SharedObjectEvent
src/clientdll/steamp2pvoice.cpp (163) : s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
src/clientdll/steamp2pvoice.cpp (163) : s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
No minidump written, nothing to upload.
StartThread called
StartThread called
ThreadMain calleddded
StartThread called
ComputerInUseThread started
Connected
Starting JobLoginPolling
Started JobLoginPolling
Already connected to CM's
StartThread called
Starting JobLoginPolling
Started JobLoginPolling
Already connected to CM's
Starting JobLoginPolling
Started JobLoginPolling
Token received, shutting down polling
StartThread called
StartThread called
zsh: segmentation fault (core dumped)  opensteam
```

</details>

<details>
<summary>Using username & password:</summary>

```
❯ opensteam
Initialized thread CallbackThread
Initialized thread LoginThread
Initialized thread ComputerInUse

(opensteam:1695795): dbind-WARNING **: 13:42:31.296: Couldn't connect to accessibility bus: Failed to connect to socket /run/user/1000/at-spi/bus_1: No such file or directory
qt.dbus.integration: Could not connect "org.freedesktop.IBus" to globalEngineChanged(QString)
Relaunching
Initialized thread CallbackThread
Initialized thread LoginThread
Initialized thread ComputerInUse

(opensteam:1695795): dbind-WARNING **: 13:42:31.390: Couldn't connect to accessibility bus: Failed to connect to socket /run/user/1000/at-spi/bus_1: No such file or directory
qt.dbus.integration: Could not connect "org.freedesktop.IBus" to globalEngineChanged(QString)
Launched correctly, opensteam_marker is inside this directory
Starting GUI
Steam client service's PID is 1695810
Starting CallbackThread
Started CallbackThread
Starting LoginThread
Started LoginThread
Starting ComputerInUse
Started ComputerInUse
steamclient.so Found CLIENTENGINE_INTERFACE_VERSION005 at 0x7f798bd84f00
Creating new GlobalUser
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Forced create but already created for SharedObjectEvent
Forced create but already created for SharedObjectEvent
src/clientdll/steamp2pvoice.cpp (163) : s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
src/clientdll/steamp2pvoice.cpp (163) : s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
assert_20230427134231_12.dmp[1695836]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230427134231_12.dmp
CreateBoundSocket: ::bind couldn't find an open port between 27060 and 27060
StartThread called
StartThread called
ThreadMain calleddded
StartThread called
ComputerInUseThread started
assert_20230427134231_12.dmp[1695836]: Finished uploading minidump (out-of-process): success = yes
assert_20230427134231_12.dmp[1695836]: response: Discarded=1
assert_20230427134231_12.dmp[1695836]: file ''/tmp/dumps/assert_20230427134231_12.dmp'', upload yes: ''Discarded=1''
Connected
Starting JobLoginPolling
Started JobLoginPolling
StartThread called
Already connected to CM's
Starting JobLoginPolling
Started JobLoginPolling
StartThread called
Token received, shutting down polling
zsh: segmentation fault (core dumped)  opensteam
```

</details>

**Comment by mantarimay** [comment] 2023-04-27 21:15
i have same issue 
```
may@localhost:~> opensteam 
/usr/lib64/opensteam/opensteam: /lib64/libcurl.so.4: no version information available (required by /usr/lib64/opensteam/opensteam)
Initialized thread CallbackThread
Initialized thread LoginThread
Initialized thread ComputerInUse
Relaunching
/usr/lib64/opensteam/opensteam: /lib64/libcurl.so.4: no version information available (required by /usr/lib64/opensteam/opensteam)
Initialized thread CallbackThread
Initialized thread LoginThread
Initialized thread ComputerInUse
Launched correctly, opensteam_marker is inside this directory
Starting GUI
Steam client service's PID is 22608
Starting CallbackThread
Started CallbackThread
Starting LoginThread
Started LoginThread
Starting ComputerInUse
Started ComputerInUse
steamclient.so Found CLIENTENGINE_INTERFACE_VERSION005 at 0x7f85bed84f00
Creating new GlobalUser
src/clientdll/steamp2pvoice.cpp (163) : s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
src/clientdll/steamp2pvoice.cpp (163) : s_libVideoFuncs.InitFunctions( LIBVIDEO_LIBRARY_NAME )
CAppInfoCacheReadFromDiskThread took 137 milliseconds to initialize
No minidump written, nothing to upload.
warning: queue 0x55e79da593b0 destroyed while proxies still attached:
  wl_callback@28 still attached
  wl_surface@26 still attached
StartThread called
StartThread called
StartThread called
ThreadMain calleddded
ComputerInUseThread started
Couldn't set video mode: Could not get EGL display
[2023-04-28 04:12:15.342] [MANGOHUD] [info] [blacklist.cpp:58] process 'vulkandriverquery' is blacklisted in MangoHud
[2023-04-28 04:12:15.342] [MANGOHUD] [info] [blacklist.cpp:58] process 'vulkandriverquery' is blacklisted in MangoHud
MESA-INTEL: warning: Haswell Vulkan support is incomplete
[2023-04-28 04:12:15.347] [MANGOHUD] [info] [config.cpp:123] parsing config: '/home/may/.config/MangoHud/MangoHud.conf'
MESA-INTEL: warning: Haswell Vulkan support is incomplete
Connected
Starting JobLoginPolling
Started JobLoginPolling
StartThread called
Token received, shutting down polling
Segmentation fault (core dumped)
```

**Comment by 20PercentRendered** [comment] 2023-04-27 21:46
I'm aware of the issue and have reproduced it successfully. Currently debugging

**Comment by 20PercentRendered** [comment] 2023-04-27 22:02
Fixed the issue. Update available in AUR, currently building a .deb release.

**Comment by 20PercentRendered** [comment] 2023-04-27 22:06
Created new release. Reopen if still reproducible.

**Comment by yochananmarqos** [comment] 2023-04-27 22:13
With v0.0.2-beta it immediately pops up a dialog saying, 

```
Failed to log on.

Error code is 77
```

Scanning the QR code in the Steam Android app did nothing, but using username and password did work.

By the way, I have no option to reopen the issue.


Are you sure this is in Beta? Is it feature complete? I'd say it's an early Alpha: 

![image](https://user-images.githubusercontent.com/5437803/235002360-6c934194-a822-4b2a-ba8d-2202c310499b.png)

**Comment by 20PercentRendered** [comment] 2023-04-27 22:27
I suppose you make a fair point about that alpha vs beta thing. It's still a long while to go before it's daily drivable for me.

Strange, QR Codes work for me. It can take a while sometimes, have you tried waiting a minute or two after scanning?

**Comment by yochananmarqos** [comment] 2023-04-27 22:32
There should be a warning that using this program breaks Steam itself. I had chosen the menu option to restore Valve's Steam, but when I run Steam I'm presented with a dialog that says , "Couldn't find Steam content, did you move it?" I had to select the Reinstall button.

**Comment by 20PercentRendered** [comment] 2023-04-27 22:34
That button doesn't actually do anything yet. The readme has instructions on how to restore original steam.

**Comment by 20PercentRendered** [comment] 2023-04-27 22:35
Actually, there is a warning. It's titled "After Install (Important)".

**Comment by yochananmarqos** [comment] 2023-04-27 22:36
Where? I didn't see anything.

**Comment by 20PercentRendered** [comment] 2023-04-27 22:41
If you want to completely get rid of opensteam, just delete .steam and rename .valvesteam to .steam, then in .local/share do the same thing except for ValveSteam and Steam. Your settings and other official client stuff is kept in .valvesteam.

**Comment by yochananmarqos** [comment] 2023-04-27 22:48
`opensteam --bootstrapper-restore-valvesteam` worked fine.

**Comment by 20PercentRendered** [comment] 2023-05-09 21:13
The crashes should be fixed now. Please retest.

**Comment by 20PercentRendered** [comment] 2023-06-03 01:05
Closed due to inactivity.

**Closed by 20PercentRendered** 2023-06-03 01:05 UTC
Labels: bug, awaiting retest
